import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import BtnPerfil from './component/btnperfil'
import VertMenu from './component/vertmenu'
import LayoutProvider from './component/layout/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Agenda Pro',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <LayoutProvider>
      {children}
    </LayoutProvider>
  )
}
